export const componentTypes = {
  GENERIC: 'GENERIC',
  CONTAINER: 'CONTAINER',
  CONTAINER_ITEM: 'CONTAINER ITEM',
  BACKGROUND: 'BACKGROUND',
  PAGE: 'PAGE',

  // ADDABLES
  FEED: 'FEED',
  STATISTICS: 'STATISTICS',
  RULES: 'RULES',
  TEXT: 'TEXT',
  FORMS: 'FORMS',
  LINKS: 'LINKS',
  ICONS: 'ICONS',
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  GALLERY: 'GALLERY',
  WIDGET: 'WIDGET',
  EMBED: 'EMBED',
  SEARCH_BAR: 'SEARCH_BAR',
  DIVIDER: 'DIVIDER',
};
