export const builderStateConstants = {
  ADD_ELEMENT: 'BUILDER_STATE_ADD_ELEMENT',
  MOVE_ELEMENT: 'BUILDER_STATE_MOVE_ELEMENT',
  SELECT_ACTIVE_ELEMENT: 'BUILDER_STATE_SELECT_ACTIVE_ELEMENT',
  UPDATE_ACTIVE_ELEMENT: 'BUILDER_STATE_UPDATE_ACTIVE_ELEMENT',
};
