export const builderStateConstants = {
  ADD_ELEMENT_REQUEST: 'BUILDER_STATE_ADD_ELEMENT_REQUEST',
  MOVE_ELEMENT_REQUEST: 'BUILDER_STATE_REQUEST_MOVE_ELEMENT_REQUEST',
  SELECT_ACTIVE_ELEMENT_REQUEST: 'BUILDER_STATE_SELECT_ACTIVE_ELEMENT_REQUEST',
  UPDATE_ACTIVE_ELEMENT_REQUEST: 'BUILDER_STATE_UPDATE_ACTIVE_ELEMENT_REQUEST',

  ADD_ELEMENT_SUCCESS: 'BUILDER_STATE_ADD_ELEMENT_SUCCESS',
  MOVE_ELEMENT_SUCCESS: 'BUILDER_STATE_MOVE_ELEMENT_SUCCESS',
  SELECT_ACTIVE_ELEMENT_SUCCESS: 'BUILDER_STATE_SELECT_ACTIVE_ELEMENT_SUCCESS',
  UPDATE_ACTIVE_ELEMENT_SUCCESS: 'BUILDER_STATE_UPDATE_ACTIVE_ELEMENT_SUCCESS',

  ADD_ELEMENT_FAILURE: 'BUILDER_STATE_ADD_ELEMENT_FAILURE',
  MOVE_ELEMENT_FAILURE: 'BUILDER_STATE_MOVE_ELEMENT_FAILURE',
  SELECT_ACTIVE_ELEMENT_FAILURE: 'BUILDER_STATE_SELECT_ACTIVE_ELEMENT_FAILURE',
  UPDATE_ACTIVE_ELEMENT_FAILURE: 'BUILDER_STATE_UPDATE_ACTIVE_ELEMENT_FAILURE',
};
