const editorConstants = {
  SAVE_REQUEST: "EDITOR_SAVE_REQUEST",
  SAVE_SUCCESS: "EDITOR_SAVE_SUCCESS",
  SAVE_FAILURE: "EDITOR_SAVE_FAILURE",

  DISCARD_REQUEST: "EDITOR_DISCARD_REQUEST",
  DISCARD_SUCCESS: "EDITOR_DISCARD_SUCCESS",
  DISCARD_FAILURE: "EDITOR_DISCARD_FAILURE",
};

export { editorConstants };
